### ISSUE TITLE
Ada Conformity Assessment Test Suite

### ISSUE THREAD

**Issue by senier** [Componolit/componolit-old#125]
Port (subset) of [Ada Conformity Assessment Test Suite (ACATS)](http://www.ada-auth.org/acats.html) to Genode.

**Comment by jklmnn** [comment]
Steps:
 - [ ] build port for acats
 - [ ] build single working test
 - [ ] autogenerate requirements for working tests from test list
 - [ ] autogenerate run files to run tests

**Comment by jklmnn** [comment]
Acats is already available in the GCC port under `contrib/gcc-.../src/noux-pkg/gcc/gcc/testsuite/ada/acats`.

**Comment by jklmnn** [comment]
With https://github.com/jklmnn/genode/commit/f756aa1053e7e39756cebdfc556ca6e6e7d13e39 I'm able to run the a22006b test with `make run/acats/a22006b`.
To simplify autogeneration I tried to make the code as generic as possible. Currently the following parts need to be modified to create a new test:
 - the `test` variable in the run file
 - `TEST_PREFIX` and `TEST` in target.mk
 - function name in startup.cc (this could be improved by using a generic startup.cc that includes a macro which selects the correct test)

**Comment by jklmnn** [comment]
With https://github.com/jklmnn/genode/commit/9b78f46c15afe4a954650296383cff2de7772325 a test can be autogenerated from its identifier and path prefix.
To create the test for `contrib/gcc-<hash>/src/noux-pkg/gcc/gcc/testsuite/ada/acats/tests/a/a22006b.ada` run `tool/acats a/22006b` which will generate the corresponding target and runfile. The test can then be executed by running `make run/acats/a/a22006b` in the build directory.

**Comment by jklmnn** [comment]
Out of the 1820 test 233 compile and 1587 fail. While I didn't analyze it I suspect that most of the fails are caused by missing interfaces (such as `Ada.Text_IO`). Also some tests consist of multiple files which is not considered by the generation script yet. These will create multiple fails (one for each file in the single test).

Some of the compiling tests are still failing by their content.

The currently compiling tests are:
```
a/a22006b
a/a22006c
a/a22006d
a/a27003a
a/a33003a
a/a34017c
a/a35101b
a/a35402a
a/a35801f
a/a35902c
a/a49027a
a/a49027b
a/a55b12a
a/a55b13a
a/a55b14a
a/a73001i
a/a73001j
a/a74105b
a/a74106a
a/a74106b
a/a74106c
a/a83009a
a/a83009b
a/a83a02a
a/a83a06a
a/a83c01c
a/a83c01h
a/a83c01i
a/a85007d
a/ac1015b
a/ac3206a
a/ad7001b
a/ad7006a
a/ad7101a
a/ad7101c
a/ad7102a
a/ad7103a
a/ad7103c
a/ad7104a
a/ae3002g
a/ae3702a
c2/c23001a
c2/c23006a
c2/c24002d
c2/c24003a
c2/c24003b
c2/c24003c
c2/c24106a
c2/c24202d
c2/c24203a
c2/c24203b
c2/c24207a
c2/c25001a
c2/c25001b
c2/c26008a
c2/c2a001a
c2/c2a001b
c2/c2a001c
c2/c2a002a
c2/c2a008a
c3/c32108a
c3/c32108b
c3/c34012a
c3/c35502g
c3/c35502h
c3/c35502o
c3/c35507h
c3/c35507j
c3/c35507p
c3/c35704a
c3/c35704b
c3/c35704c
c3/c35704d
c3/c35a02a
c3/c36205l
c3/c36301b
c3/c36302a
c3/c37103a
c3/c38102e
c4/c41320a
c4/c41321a
c4/c41322a
c4/c41323a
c4/c41324a
c4/c41327a
c4/c43214c
c4/c44003d
c4/c45114b
c4/c45201b
c4/c45202b
c4/c45210a
c4/c45211a
c4/c45220e
c4/c45220f
c4/c45265a
c4/c45347a
c4/c45347b
c4/c45347c
c4/c47002a
c4/c47002b
c4/c49020a
c4/c49021a
c4/c49022a
c4/c49022b
c4/c49022c
c4/c49024a
c4/c49025a
c4/c49026a
c4/c4a010a
c4/c4a010b
c4/c4a014a
c5/c52010a
c5/c54a03a
c5/c54a22a
c5/c54a24a
c5/c54a24b
c5/c57003a
c5/c58004c
c5/c58004d
c5/c58004g
c5/c59002b
c6/c62006a
c6/c64002b
c6/c64004g
c6/c64005a
c6/c66002a
c6/c66002c
c6/c66002d
c6/c66002e
c7/c74206a
c7/c74208b
c7/c74211b
c7/c74305a
c7/c74305b
c7/c74307a
c7/c74402a
c7/c74402b
c7/c74409b
c8/c83b02a
c8/c83e02a
c8/c83e03a
c8/c83f03a
c8/c83f03b
c8/c85007a
c8/c85019a
c8/c87a05a
c8/c87a05b
c8/c87b02a
c8/c87b02b
c8/c87b03a
c8/c87b04a
c8/c87b04b
c8/c87b04c
c8/c87b05a
c8/c87b06a
c8/c87b07a
c8/c87b07b
c8/c87b07d
c8/c87b08a
c8/c87b09a
c8/c87b09c
c8/c87b10a
c8/c87b11a
c8/c87b11b
c8/c87b13a
c8/c87b14a
c8/c87b14b
c8/c87b14c
c8/c87b14d
c8/c87b15a
c8/c87b16a
c8/c87b17a
c8/c87b18a
c8/c87b18b
c8/c87b19a
c8/c87b23a
c8/c87b24a
c8/c87b24b
c8/c87b27a
c8/c87b29a
c8/c87b30a
c8/c87b33a
c8/c87b34a
c8/c87b34b
c8/c87b34c
c8/c87b38a
c8/c87b42a
c8/c87b43a
c8/c87b44a
c8/c87b45a
c8/c87b47a
c8/c87b48a
c8/c87b48b
c8/c87b50a
c8/c87b57a
c8/c87b62a
c8/c87b62c
ca/ca1011a0
ca/ca1011a2
ca/ca1011a4
cc/cc1010a
cc/cc1010b
cc/cc1018a
cc/cc1304a
cc/cc1307a
cc/cc1307b
cc/cc3011d
cc/cc3015a
cc/cc3016c
cc/cc3016i
cc/cc3230a
cc/cc3236a
cc/cc3240a
cc/cc3606a
cd/cd1009b
cd/cd1009d
cd/cd1009l
cd/cd1009n
cd/cd1009p
cd/cd1009x
cd/cd1009y
cd/cd1009z
cd/cd1c03i
cd/cd2d13a
cd/cd4031a
cd/cd7007b
cd/cd7101d
cd/cd7103d
cd/cd7305a
d/d4a002a
d/d4a002b
d/d4a004a
d/d4a004b
```

**Comment by jklmnn** [comment]
For a better automatized test creation the [ACATS-UG](http://www.ada-auth.org/acats-files/3.0/docs/ACATS-UG.PDF) describes the file name conventions.

**Comment by jklmnn** [comment]
I tested all passing builds and only the `ca1011ax.ada` tests fail. All other tests passed. Also I should rework the output format to parse test id, description and result.

What is strange about the `ca1011ax.ada` tests are the error messages. Usually a test should start with the `TEST` function and either call `PASSED` or `FAILED`. Theses tests only call `FAILED` without calling `TEST` or providing a description. Maybe there's missing more.
