### ISSUE TITLE
Genode package

### ISSUE THREAD

**Issue by jklmnn** [Componolit/componolit-old#127]
Create a Genode package on Ada that provides an interface to Genode functions in Ada.

There are two design options:
 - directly use child packages (e.g. Genode.Base.Log.Log())
 - create a Genode package that renames other packages (e.g. Base.Log.Log() -> Genode.Log())

**Comment by jklmnn** [comment]
With https://github.com/jklmnn/genode/commit/16b147342177c0df3e7c9decd600a9d187df9f9d I added Genodes logging functions and with https://github.com/jklmnn/genode/commit/d9d732f69f00a94421c91088fabe660334e8e7a9 I moved the namespace to `Genode.*`.
The resulting library is `ada-genode.lib.so` and the functions can be used by
```
with Genode;
...
Genode.Log("...");
```

**Comment by jklmnn** [comment]
#132 is closed and discussed here

There are currently three major problems:
 - [ ] The autogenerated code contains contructs like `type util_meta_h.Empty is record` that are not allowed in Ada (note the `.` in the record name).
 - [ ] C++ functions starting with an underscore are ignored and ommitted with a comment `--  skipped func _underscore`.
 - [ ] The generated spec does not reflect Genodes namespace hierarchy and creates package names from file paths, namespaces and class names with underscores which is a rather ugly interface.

**Comment by jklmnn** [comment]
Autogeneration could also be done with https://github.com/ytomino/headmaster.

**Comment by jklmnn** [comment]
I tried to build headmaster on multiple systems now (Debian 9, Ubuntu 17.10, 18.04) and it always failed to build with various errors. It seems to use a quite new version of ocaml (the version provided with Ubuntu 18.04 was to old) and even reverting the commits that required a newer version (as stated in https://github.com/ytomino/headmaster/issues/4) did not solve the issues.
Current state is that on Ubuntu 18.04 the build fails with
```
make: Verzeichnis „/.../headmaster/main“ wird betreten
echo "let version = \"version 0.29-17159d8 (devel)\";;" > version.ml
ocamlbuild -build-dir x86_64-linux-gnu.build -X x86_64-linux-gnu.build -X bin -I source -I source/ada -cflags "-g -safe-string -w Aer-48" main.native
Finished, 0 targets (0 cached) in 00:00:00.
+ /usr/bin/ocamlc.opt -c -g -safe-string -w Aer-48 -I . -I . -I . -I source -I source/ada -o main.cmo main.ml
File "main.ml", line 1:
Error: The files /usr/lib/ocaml/pervasives.cmi and gmp.cmi
       make inconsistent assumptions over interface Pervasives
Command exited with code 2.
```
and on Debian 9 it fails with
```
make: Verzeichnis „/.../headmaster/main“ wird betreten
ocamlbuild -build-dir x86_64-linux-gnu.build -X x86_64-linux-gnu.build -X bin -I source -I source/ada -cflags "-g -safe-string -w Aer-48" main.native
Finished, 0 targets (0 cached) in 00:00:00.
+ /usr/bin/ocamlc.opt -c -g -safe-string -w Aer-48 -I source -I source/ada -o source/c_semantics.cmo source/c_semantics.ml
File "source/c_semantics.ml", line 9, characters 8-16:
Error: Unbound value find_opt
Command exited with code 2.
Compilation unsuccessful after building 19 targets (18 cached) in 00:00:00.
```

**Comment by jklmnn** [comment]
I was able to build the headmaster project (at least the build exited without visible errors).
On Debian you currently have remove all system packages of ocaml (good bye frama-c btw) since the Makefile somehow doesn't check the path correctly.
The required compiler can be installed with `opam switch install 4.06.1` also `ocamlbuild` needs to be installed with opam.
Furthermore the following patch is required on Debian:
```
diff --git a/main/Makefile b/main/Makefile
index 8e299a0..4b3fdda 100644
--- a/main/Makefile
+++ b/main/Makefile
@@ -67,7 +67,7 @@ man1:
        mkdir man1
 
 man1/headmaster.1: headmaster.1.rst version.rst | man1
-       rst2man.py $< $@
+       rst2man $< $@
 
 version.rst: version.txt version $(HEAD)
        echo ".. |version| replace:: $(shell ./version)" > version.rst
```

**Comment by jklmnn** [comment]
Also make sure that you either already have a directory `~/bin` existing or call `make -C main install BINDIR=$HOME/bin/` (note the trailing `/`) because otherwise it will install the executable as `~/bin` into your home directory.

**Comment by jklmnn** [comment]
https://github.com/ytomino/headmaster/issues/6 and https://github.com/ytomino/headmaster/issues/7 should have fixed the issues I described.

**Comment by senier** [comment]
Good to see the author reacting so quickly upon issues!

**Comment by ytomino** [comment]
Hello. I'm an author of headmaster, and found this issue by the above referenced link.

According to #132, are you trying to convert C++?
If so, sorry that it could not meet your expectations because headmaster does not support C++ syntax...

**Comment by senier** [comment]
Hi @ytomino,

thanks for joining the discussion :-) Indeed, we're trying to convert C++ (and, actually not the most trivial subset) to generate Ada/SPARK bindings for the Genode OS Framework. We tried gcc's dump-specs feature an it turned out to be not quite perfect. For some reason I had the false impression that headmaster would support C++. Thanks for clarifying!

Still, headmaster looks like an interesting tool (and interesting language choices - Ocaml to convert C to Ada). Keep it up! Can you share why you built it in favor of using gcc?

**Comment by ytomino** [comment]
Hi, @senier.

> We tried gcc's dump-specs feature an it turned out to be not quite perfect.

I can understand :-(

> Ocaml to convert C to Ada

https://github.com/cil-project/cil
CIL has existed as nice precedent of C parser implemented with OCaml.
I didn't use it in headmaster for some reasons (C preprocessor is not integrated, etc), but it's a great library as reference.

> Can you share why you built it in favor of using gcc?

Well, headmaster is not so strongly depending on gcc. Merely headmaster queries gcc for its search paths and predefined macros. Perhaps gcc can be replaced by clang easily with little changing.
...Is this an answer?

> Keep it up!

Thank you so much.
Excuse me for interrupting your discussion.
