### ISSUE TITLE
TCP/IP stack

### ISSUE THREAD

**Issue by jklmnn** [Componolit/componolit-old#138]
We need a working and reliable TCP/IP stack. LWIP is broken and since Genode 18.05 marked as legacy.
The only current alternative seems to be LXIP.

**Comment by jklmnn** [comment]
Just for completeness:
with the lwip-legacy port I get the following error within 200 requests:
```
Assertion "tcpip_thread: invalid message" failed at /.../contrib/lwip_legacy-7f5610426ed8c4c64903136122d9ba58836cdc89/src/lib/lwip_legacy/src/api/tcpip.c:151
```

**Comment by jklmnn** [comment]
I tried to adapt our tcp echo server to your lwip port but vfs seems to fail to find a feasible plugin. Yet it shows lwip (correctly I assume?):
```
Genode 18.05-132-ge28d0dcfe9
468 MiB RAM and 63253 caps assigned to init
[init -> vfs]   0xa0000000 .. 0xafffffff: stack area
[init -> vfs]   0x30000 .. 0x147fff: ld.lib.so
[init -> vfs]   0x1036000 .. 0x10a2fff: vfs.lib.so
[init -> nic_drv] --- iPXE NIC driver started ---
[init -> nic_drv] -- init iPXE NIC
[init -> test-tcp_echo_server]   0xa0000000 .. 0xafffffff: stack area
[init -> test-tcp_echo_server]   0x30000 .. 0x147fff: ld.lib.so
[init -> test-tcp_echo_server]   0x1004000 .. 0x116efff: libc.lib.so
[init -> test-tcp_echo_server]   0x116f000 .. 0x11dbfff: vfs.lib.so
[init -> vfs]   0x10a3000 .. 0x10eafff: vfs_lwip.lib.so
[init -> acpi_drv] Found MADT
[init -> acpi_drv] MADT IRQ 0 -> GSI 2 flags: 0
[init -> acpi_drv] MADT IRQ 5 -> GSI 5 flags: 13
[init -> acpi_drv] MADT IRQ 9 -> GSI 9 flags: 13
[init -> acpi_drv] MADT IRQ 10 -> GSI 10 flags: 13
[init -> acpi_drv] MADT IRQ 11 -> GSI 11 flags: 13
[init -> acpi_drv] Found MCFG
[init -> acpi_drv] MCFG BASE 0xb0000000 seg 0x0 bus 0x0-0xff
[init -> acpi_drv] RSDT OEM 'BOCHS ', table id 'BXPCRSDT', revision 1, creator 'BXPC' (1)
[init -> platform_drv] ECAM/MMCONF range 00:00.0-ff:1f.7 - addr [00000000b0000000,00000000c0000000)
[init -> platform_drv] Root bridge: 00:00.0
[init -> nic_drv] Found: 00:02.0 8086:100e (rev 03) IRQ 0b
[init -> nic_drv] using driver 82540em
[init -> nic_drv] PCI device 00:02.0 latency timer is unreasonably low at 0. Setting to 32.
[init -> nic_drv] 
[init -> nic_drv] bus_addr = febc0000 len = 20000
[init -> nic_drv] snprintf not implemented
[init -> platform_drv] IRQ override 11->11, trigger mode: LEVEL, polarity: HIGH
[init -> platform_drv] 00:02.0 uses IRQ, vector 0xb, non-maskable
[init -> nic_drv] MAC address 52:54:00:12:34:56
[init -> vfs] configuring lwIP interface with DHCP
[init -> vfs]   0x10eb000 .. 0x1101fff: vfs_audit.lib.so
[init -> vfs] session opened for 'test-tcp_echo_server -> ' at '/socket'
[init -> test-tcp_echo_server] tcp_echo_server
[init -> test-tcp_echo_server] Error: no plugin found for socket()
[init -> test-tcp_echo_server] Error: Failed to open socket: -1
[init -> test-tcp_echo_server] Error: no plugin found for bind(-1)
[init -> test-tcp_echo_server] Error: Failed to bind: -1
[init -> test-tcp_echo_server] Error: no plugin found for listen(-1)
[init -> test-tcp_echo_server] Error: no plugin found for accept(-1)
[init -> test-tcp_echo_server] Error: accept failed -1
```

**Comment by ehmry** [comment]
Traditionally there were two libc "plugins" that provided socket support, LwIP and LxIP. The plan is to convert both to VFS plugins, and the libc will have a single socket implementation, one that uses special files found in the VFS. For now only LxIP is converted to the VFS, and VFS socket support is implemented in weak symbols in the VFS so that LwIP can still override them.

I am in the process of finishing the LwIP VFS plugin, which should make things less confusing.

**Comment by ehmry** [comment]
The libraries libc_lwip, libc_lwip_loopback, and libc_lwip_nic_dhcp need to be avoided as well.

**Comment by jklmnn** [comment]
I have already removed these libraries from my target.mk but the error still occurs.
my build components:
```
core
init
drivers/timer drivers/nic
test/tcp_echo_server
server/vfs
lib/vfs/lwip
lib/vfs/audit
```
and my boot components:
```
core
ld.lib.so
libc.lib.so
vfs.lib.so
vfs_audit.lib.so
vfs_lwip.lib.so
init
timer
} [nic_drv_binary] {
vfs
test-tcp_echo_server
```
Did I miss something? As I said the only component that is using libc is the `tcp_echo_server` which only has `LIBS = libc`.

**Comment by ehmry** [comment]
Can you post the configuration of `tcp_echo_server`?

**Comment by jklmnn** [comment]
```
    <start name="test-tcp_echo_server">
        <resource name="RAM" quantum="8M"/>
        <config ld_verbose="yes">
            <vfs>
                <dir name="dev"><log/></dir>
                <dir name="socket"><fs/></dir>
                <dir name="tmp"><ram/></dir>
            </vfs>
        </config>
    </start>
```

**Comment by jklmnn** [comment]
If you want to reproduce it you can use the `componolit-stable_lwip` branch of my Genode fork and the [Componolit](https://github.com/jklmnn/componolit/tree/http_proxy_lwip) repo (at branch `http_proxy_lwip`) and run `run/tcp_echo_server`.

**Comment by ehmry** [comment]
The test runs when I add `<libc socket="/socket"/>` to the test's configuration. It surprises me because I thought this was a default configuration that was in place, but I suppose we never agreed on what that default should be.

```
    <start name="test-tcp_echo_server">
        <resource name="RAM" quantum="8M"/>
        <config ld_verbose="yes">
		<libc socket="/socket"/>
            <vfs>
                <dir name="dev"><log/></dir>
                <dir name="socket"><fs/></dir>
                <dir name="tmp"><ram/></dir>
            </vfs>
        </config>
    </start>
```

**Comment by chelmuth** [comment]
IIRC we had some agreement that our run script will configure `socket="/socket"` and not `/dev/`. And no, we have no default configuration for the socket path and this should also be logged according to https://github.com/genodelabs/genode/blob/master/repos/libports/src/lib/libc/socket_fs_plugin.cc#L795

**Comment by jklmnn** [comment]
I tried adding `<libc socket="/socket"/>` resolved the original issue. Yet I get page faults in my connection threads now. As a short explanation:
Since I can't block in the Main function (and since I have return from it) I start a separate thread that runs the TCP server and stays in a loop calling `accept`. When a `accept` returns and a connection is opened the server thread starts a connection thread which handles the connection traffic (basically a read-write loop in this case) so the server can return to `accept` immediately and handle new connections. 
This architecture worked fine with the old lwip implementation but with the new one the connection thread creates a page fault or sometimes the server thread stops with an invalid file handle.
Are there any changes that could introduce this kind of behaviour?
@ehmry have you tried to connect to the server (port 5555 on localhost with the runfile provided)?

**Comment by ehmry** [comment]
I am getting a fault as well when I connect, and I am investigating it.

Using POSIX `select`is recommended over running multiple threads, the socket_fs should be fully asynchronous and is most heavily tested in this way.
