### ISSUE TITLE
Alternate implementation of art::Exec using sub-init

### ISSUE THREAD

**Issue by senier** [Componolit/componolit-old#95]
The library implementation of art::Exec done in #89 works for basic cases where no global variables are modified. When `getopt` is reset manually, programs like `rm`, `diff`or `unzip` work when linked into the current address space using `dlopen()`.

The approach fails as soon as "programs" are executed from ART that also use ART libraries. Namely `dexdump2`, `dexlayout` and probably also `dex2oat` fail with assertions that most likely result from improperly shared state between the calling ART instance and executed tool.

A different approach for `art::Exec` must be implemented. Current idea: The ART instance gets access to the config ROM of a sub-init. This config ROM could be provided though `fs_rom` using the same filesystem session the ART instance is using. This way, ART could change init's config through the standard POSIX interfaces (this would required changes in the FS to be signaled through to the ROM session - is that true?).

When `art::Exec` is called, a library function modifies init's configuration to execute the desired binary. Command line arguments are provided through the component configuration. The file system of the started program could be the same FS session shared between init and the ART instance. Binaries could be provided either through `fs_rom` or through a different, global ROM session.

**Comment by nfeske** [comment]
It is cool to see that you are considering the dynamic init approach. As inspiration, you may have a look at the depot-download subsystem as featured in the gems repository of Genode 18.02. The subsystem looks as follows: https://github.com/genodelabs/genode/blob/master/repos/gems/recipes/raw/depot_download/depot_download.config The central component is the download manager. You can find the implementation at https://github.com/genodelabs/genode/tree/master/repos/gems/src/app/depot_download_manager

**Comment by senier** [comment]
Exciting - I was about to write a mail to the list to ask for those details. Thanks for pointing that out!
