### ISSUE TITLE
Implement or port diff/cmp tool

### ISSUE THREAD

**Issue by senier** [Componolit/componolit-old#96]
The library version done in #93 did not work out. A full port of a BSD diff turned out to be extremely complicated. We should find a simpler alternative, as `diff` is really only used to check for equality of files in the test cases. A port (or implementation) of the simple `cmp` tool should suffice.

**Comment by jklmnn** [comment]
I don't know in what context the files are being compared (e.g. as Genode ROM sessions) but wouldn't it be sufficient to run memcmp on a file? Or start comparing and break on the first different byte.

**Comment by senier** [comment]
The ART tests expect a program that they call with two files as an argument (on Linux fork/exec is used, in our port libexec in conjunction with the apphost server is used). While a simple memcmp approach might be possible, we don't want to read all file content into memory (files will be huge!). So at least we need to compare files in chunks.

While a simple stop-at-first-mismatch approach will most likely work, a real diff may be beneficial if a test fails to identify the cause of the problem. I will see whether I can find something simple (the BSD stuff wasn't and the GNU diffutils stuff for sure isn't.)

**Comment by jklmnn** [comment]
Maybe a look into rsync could be worth it. While it won't give exactly diffs, it is designed to create and check chunks for equality so save bandwidth. This requires that the mechanisms used are understandable and modularized enough to be ported with moderate effort.
