### ISSUE TITLE
Reading ZIP fails on VFS server

### ISSUE THREAD

**Issue by senier** [Componolit/componolit-old#97]
After switching from a local vfs to servicing requests in a vfs server, reading ZIP archives (which includes handling JARs art runtime startup) fails:

```
[init -> libart-dexlayout_test] E/ziparchive(   42):
[init -> libart-dexlayout_test] Zip: failed to read at offset 2201684
[init -> libart-dexlayout_test] E/ziparchive(   42):
[init -> libart-dexlayout_test] Zip: read 65557 from offset 2201684 failed
[init -> libart-dexlayout_test] E/ziparchive(   42):
[init -> libart-dexlayout_test] Zip: failed to read at offset 1331829
[init -> libart-dexlayout_test] E/ziparchive(   42):
[init -> libart-dexlayout_test] Zip: read 65557 from offset 1331829 failed
```

This error comes from code in `zip_archive.cc`:

```c++
  if (!archive->mapped_zip.ReadAtOffset(scan_buffer, read_amount, search_start)) {
    ALOGE("Zip: read %" PRId64 " from offset %" PRId64 " failed", static_cast<int64_t>(read_amount),
          static_cast<int64_t>(search_start));
    return kIoError;
  }
```

`ReadAtOffset` is implemented in the same file

```c++
    if (static_cast<size_t>(TEMP_FAILURE_RETRY(pread64(fd_, buf, len, off))) != len) {
      ALOGE("Zip: failed to read at offset %" PRId64 "\n", off);                                                                               
      return false;
    }
```

Hence, `pread64` is the suspect. Next step: Create a stand-alone test case working on local VFS and VFS server.

**Comment by senier** [comment]
After instrumenting a bit more, this smells like an off-by-one error either in Android or Genode's VFS:

```
[init -> libart-dexlayout_test] MapCentralDirectory0(//android/framework/core-oj-hostdex.jar, *, file_length=2267241 read_amount=65557)
[init -> libart-dexlayout_test] E/ziparchive(   42):
[init -> libart-dexlayout_test] Zip: failed to read at offset 2201684

[init -> libart-dexlayout_test] MapCentralDirectory0(//android/framework/core-libart-hostdex.jar, *, file_length=1397386 read_amount=65557)
[init -> libart-dexlayout_test] E/ziparchive(   42):
[init -> libart-dexlayout_test] Zip: failed to read at offset 1331829
```

Adding up `offset` and `read_amount` exactly equals `file_length` in both cases.

**Comment by senier** [comment]
Looks like Android is relying on the false assumption that `pread(fd, buf, len, off)` always yields `len` bytes as a result in `zip_archive.cc:1166`.

The Linux man page on [pread(2)](http://man7.org/linux/man-pages/man2/pread.2.html) states:

> Note that is not an error for a successful call to transfer fewer
> bytes than requested (see read(2) and write(2)).

**Comment by nfeske** [comment]
This seems to be closely related to https://github.com/genodelabs/genode/issues/2714

I think we (Genode's libc) should ultimately satisfy Android's (arguably false but very common) assumption.
